# Generated by Django 4.2.11 on 2024-03-30 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=100)),
                ('uc', models.CharField(max_length=100)),
                ('turno', models.CharField(max_length=100)),
                ('turma', models.CharField(max_length=100)),
                ('inscritos', models.IntegerField()),
                ('dia', models.DateField()),
                ('horaInicio', models.TimeField()),
                ('horaFim', models.TimeField()),
                ('data', models.DateField()),
                ('caracteristicas', models.CharField(max_length=255)),
                ('sala', models.CharField(max_length=100)),
                ('semanaAno', models.IntegerField()),
                ('semanaSemestre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edificio', models.CharField(max_length=100)),
                ('nomeSala', models.CharField(max_length=100)),
                ('capacidadeNormal', models.IntegerField()),
                ('capacidadeExame', models.IntegerField()),
                ('numCaracteristicas', models.IntegerField()),
                ('anfiteatro', models.BooleanField()),
                ('apoioTecnicoEventos', models.BooleanField()),
                ('arq1', models.BooleanField()),
                ('arq2', models.BooleanField()),
                ('arq3', models.BooleanField()),
                ('arq4', models.BooleanField()),
                ('arq5', models.BooleanField()),
                ('arq6', models.BooleanField()),
                ('arq9', models.BooleanField()),
                ('byod', models.BooleanField()),
                ('focusGroup', models.BooleanField()),
                ('horarioVisivelPub', models.BooleanField()),
                ('labArqI', models.BooleanField()),
                ('labArqII', models.BooleanField()),
                ('labBasesEng', models.BooleanField()),
                ('labEletro', models.BooleanField()),
                ('labInfo', models.BooleanField()),
                ('labJornalismo', models.BooleanField()),
                ('labRedesCompI', models.BooleanField()),
                ('labRedesCompII', models.BooleanField()),
                ('labTele', models.BooleanField()),
                ('salaAulasMestrado', models.BooleanField()),
                ('salaAulasMestradoPlus', models.BooleanField()),
                ('salaNee', models.BooleanField()),
                ('salaProvas', models.BooleanField()),
                ('salaReuniao', models.BooleanField()),
                ('salaArquitetura', models.BooleanField()),
                ('salaAulaNormal', models.BooleanField()),
                ('videoconferencia', models.BooleanField()),
                ('atrio', models.BooleanField()),
            ],
        ),
    ]
