# Generated by Django 4.2.11 on 2024-03-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaodehorarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracterizacaodassalas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edificio', models.TextField(blank=True, db_column='Edifício', null=True)),
                ('nome_sala', models.TextField(blank=True, db_column='Nome sala', null=True)),
                ('capacidade_normal', models.IntegerField(blank=True, db_column='Capacidade Normal', null=True)),
                ('capacidade_exame', models.IntegerField(blank=True, db_column='Capacidade Exame', null=True)),
                ('n_caracteristicas', models.IntegerField(blank=True, db_column='Nº características', null=True)),
                ('anfiteatro_aulas', models.TextField(blank=True, db_column='Anfiteatro aulas', null=True)),
                ('apoio_tecnico_eventos', models.TextField(blank=True, db_column='Apoio técnico eventos', null=True)),
                ('arq_1', models.TextField(blank=True, db_column='Arq 1', null=True)),
                ('arq_2', models.TextField(blank=True, db_column='Arq 2', null=True)),
                ('arq_3', models.TextField(blank=True, db_column='Arq 3', null=True)),
                ('arq_4', models.TextField(blank=True, db_column='Arq 4', null=True)),
                ('arq_5', models.TextField(blank=True, db_column='Arq 5', null=True)),
                ('arq_6', models.TextField(blank=True, db_column='Arq 6', null=True)),
                ('arq_9', models.TextField(blank=True, db_column='Arq 9', null=True)),
                ('byod', models.TextField(blank=True, db_column='BYOD (Bring Your Own Device)', null=True)),
                ('focus_group', models.TextField(blank=True, db_column='Focus Group', null=True)),
                ('horario_visivel_publico', models.TextField(blank=True, db_column='Horário sala visível portal público', null=True)),
                ('lab_arq_comp_i', models.TextField(blank=True, db_column='Laboratório de Arquitectura de Computadores I', null=True)),
                ('lab_arq_comp_ii', models.TextField(blank=True, db_column='Laboratório de Arquitectura de Computadores II', null=True)),
                ('lab_de_bases_de_engenharia', models.TextField(blank=True, db_column='Laboratório de Bases de Engenharia', null=True)),
                ('lab_de_electro', models.TextField(blank=True, db_column='Laboratório de Electrónica', null=True)),
                ('lab_de_informatica', models.TextField(blank=True, db_column='Laboratório de Informática', null=True)),
                ('lab_de_jornalismo', models.TextField(blank=True, db_column='Laboratório de Jornalismo', null=True)),
                ('lab_redes_de_comp_i', models.TextField(blank=True, db_column='Laboratório de Redes de Computadores I', null=True)),
                ('lab_redes_de_comp_ii', models.TextField(blank=True, db_column='Laboratório de Redes de Computadores II', null=True)),
                ('lab_de_tele', models.TextField(blank=True, db_column='Laboratório de Telecomunicações', null=True)),
                ('sala_aulas_mestrado', models.TextField(blank=True, db_column='Sala Aulas Mestrado', null=True)),
                ('sala_aulas_mestrado_plus', models.TextField(blank=True, db_column='Sala Aulas Mestrado Plus', null=True)),
                ('sala_nee', models.TextField(blank=True, db_column='Sala NEE', null=True)),
                ('sala_provas', models.TextField(blank=True, db_column='Sala Provas', null=True)),
                ('sala_reuniao', models.TextField(blank=True, db_column='Sala Reunião', null=True)),
                ('sala_de_arquitectura', models.TextField(blank=True, db_column='Sala de Arquitectura', null=True)),
                ('sala_de_aulas_normal', models.TextField(blank=True, db_column='Sala de Aulas normal', null=True)),
                ('videoconferencia', models.TextField(blank=True, null=True)),
                ('atrio', models.TextField(blank=True, db_column='Átrio', null=True)),
            ],
            options={
                'db_table': 'CaracterizacaoDasSalas',
                'managed': False,
            },
        ),
    ]
